// <auto-generated />
using AXCEX_ONLINE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AXCEXONLINE.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AXCEX_ONLINE.Models.ProjectAssignment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EmpKey");

                    b.Property<int>("ProjKey");

                    b.Property<string>("authorized_assignment");

                    b.HasKey("ID");

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("AXCEX_ONLINE.Models.ProjectModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProjectID");

                    b.Property<string>("Customer")
                        .HasColumnName("CustomerName");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsActive")
                        .HasColumnName("ActiveProject");

                    b.Property<decimal>("ProjBudget")
                        .HasColumnType("money");

                    b.Property<decimal>("ProjCurentCost")
                        .HasColumnType("money");

                    b.Property<string>("ProjectName")
                        .HasColumnName("ProjectName");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("StartDate");

                    b.HasKey("ID");

                    b.ToTable("ProjectModel");
                });
#pragma warning restore 612, 618
        }
    }
}
